### ISSUE TITLE
rebuild against ncurses 6.1?

### ISSUE THREAD

**Issue by lebedov** [conda-forge/readline-feedstock#10]
Would it be possible to rebuild readline against ncurses 6.1? The libraries in the ncurses-7.0-0 package on anaconda.org appear to be linked against ncurses 5.9; this prevents it from being used alongside packages that have been upgraded to use ncurses 6.1.

**Comment by bgruening** [comment]
Yes, I think I have the same problem.

@conda-forge-admin, please rerender

**Comment by bgruening** [comment]
@lebedov https://github.com/conda-forge/readline-feedstock/pull/11

**Comment by lebedov** [comment]
Fixed in readline-7.0-ha6073c6_4.
